My ls object
misosoup160/ruby-practices pull request #2
Opened 2021-02-23 07:04 UTC by misosoup160

2021-02-27 14:26 UTC, u1tnk requested changes

2021-02-27 14:26 UTC, u1tnk commented on 08.ls_object/lib/ls.rb
> +puts LsFiles.new(pathname, **params).files_info
**とか使いこなしてるあたり、よく勉強してますね 👍

2021-02-27 14:26 UTC, u1tnk commented on 08.ls_object/lib/ls_files.rb
> +  attr_reader :pathname, :long_format, :reverse, :dot_match, :file_names, :files
attr_readerは外部に読み出す必要のある所だけ使いましょう。見える必要の無い所から見えるのは良くないです。
内部からのアクセスは `@xxx`で良いです。

2021-03-02 07:51 UTC, u1tnk requested changes

2021-03-02 07:51 UTC, u1tnk commented on 08.ls_object/lib/ls_file.rb
> +class LsFile
これでも良いですが、 Lsモジュールを作ってLs::FIleクラスにしても良いですね。

2021-03-02 07:51 UTC, u1tnk commented on 08.ls_object/lib/ls_file.rb
> +  def file_name
file_xxxという名前をよく見ますが、LsFIleオブジェクトなので `LsFIle.file_name`となってしまい冗長です。 `file_`は消して良いと思います。

2021-03-02 07:51 UTC, u1tnk commented on 08.ls_object/lib/ls_file.rb
> +  def format_type_and_mode
これは単純にフォーマットなのでFormatクラスで良さそう。

2021-03-02 07:51 UTC, u1tnk commented on 08.ls_object/lib/ls_file.rb
> +  def format_type
これはformatというより typeの省略系なので `type_abbreviation`(長いので type_abbr でも良いです。たまに見る略し方です)とか `to_type_s`とかで良いかなと思います。

ちなみに長い単語でも略さない方が分かりやすい事が多いのですが、定番の略し方があったり、利用頻度が高いときは略します。 `to_s`とか典型的ですね。

2021-03-02 07:51 UTC, u1tnk commented on 08.ls_object/lib/ls_file.rb
> +  def format_mode
こちらもformatというよりは modeの文字列を取得するメソッド名の方が良さそうですね。

2021-03-02 07:51 UTC, u1tnk commented on 08.ls_object/lib/ls_files.rb
> +  def files_info
こちらは LsFileインスタンスの配列を返しているので `files`/`ls_files` で良いと思います。
Ruby/Railsの慣習として、ある自作クラスのインスタンスの配列を返すときは そのクラスのcamel_caseの複数形となるので。

2021-03-02 07:51 UTC, u1tnk commented on 08.ls_object/lib/ls_files.rb
> +  def files_info
このメソッドは何度か呼ばれると思うのですが、毎回 ファイルアクセスしてるように見えます。
単なる計算とかならそれでも良いのですが、一般にIO処理は負荷が大きいので一回しかしないようにしましょう。
よくあるイディオムで

```
def files 
   @files ||= generate_files
end

def generate_files
...
end
```

みたいなやつもありますね。
単純にインスタンス変数に保存してデータがあったら処理をしないようにしても良いですが。

ちなみにほぼ発生しないし、課題レベルで意識する必要は無いですが、データの読み込み結果をキャッシュしないと、何度も読みこんでいると童子に外部のプロセスがファイルを作ってしまうと、途中で違う結果になってしまって、意図しない動作になる可能性も存在しますね。

2021-03-02 07:51 UTC, u1tnk commented on 08.ls_object/lib/ls_format.rb
> +  def format_data
変数やメソッドで `xxx_data`とするのはよく見かけるのですが、_dataは抽象的すぎて、ほとんどのケースで削除した方が良いですね。
ここの場合は formatというのもクラス名に入っていますし… 
よくあるパターンとしてクラスが目的を一つに絞っているような場合だと runとか executeが使われる事が多いです。
その場合は唯一のpublicメソッドになります。

2021-03-02 07:53 UTC, u1tnk commented on 08.ls_object/lib/ls_file.rb
> +MODE_TABLE = {
他のクラスで参照する定数をトップレベルに書いてしまうのはあまり良くないですね。
数ファイルしか無い規模と分かっているならアリですが、業務ではほぼ無いので基本やりません。
また、この定数は一箇所でしか参照されてないようですのでなおさらそのクラス内で定義しましょう。

2021-03-02 09:47 UTC, misosoup160 commented on 08.ls_object/lib/ls_file.rb
> +class LsFile
Lsモジュール…、FilesとFileをLsモジュールで囲うみたいなことでしょうか…？

2021-03-02 09:50 UTC, misosoup160 commented on 08.ls_object/lib/ls_file.rb
> +  def format_type_and_mode
build_dataからtype_and_mode:を消して、Formatクラスのlong_format_rowでtypeとmodeを呼んでtype_and_mode:をつくると言うことでしょうか？

2021-03-02 10:07 UTC, misosoup160 commented on 08.ls_object/lib/ls_files.rb
> +  def files_info
名前のところはls.rbの`files = LsFiles.new(pathname, **params)`でfiles使っちゃって被っちゃうとどうしようと思ってしまって…

１回だけで済むようにするところ、ちょっとよくわかってないです。
初期化時にインスタンス変数にしてしまうとnewした時しか呼ばれないです？
上のコードだとどうして呼ばれる回数が減るのか…？？？

2021-03-02 12:35 UTC, u1tnk requested changes

2021-03-02 12:35 UTC, u1tnk commented on 08.ls_object/lib/ls_file.rb
> +class LsFile
ですです。

```
module Ls
  class Files
  end
  class File
  end
end
```

って感じですね。
ファイル配置は `ls/files.rb`とかになって、それぞれで module Ls に囲まれてれば良いですね。

2021-03-02 12:35 UTC, u1tnk commented on 08.ls_object/lib/ls_file.rb
> +  def format_type_and_mode
そうですね。

Formatの役目は文字列の組立なので、それはそちらに任せちゃって良いですね。

修正するかはお任せレベルですが、私なら build_dataの中身もそれぞれバラして、Format側で以下のように組み立てちゃうかなーと思います。

```
files.each do |f|
  "#{f.type}{f.mode}   ..... "
end
```

2021-03-02 12:35 UTC, u1tnk commented on 08.ls_object/lib/ls_files.rb
> +  def files_info
> 名前のところはls.rbのfiles = LsFiles.new(pathname, **params)でfiles使っちゃって被っちゃうとどうしようと思ってしまって…

確かに！ LsFilesクラスなのか LsFileの配列なのか分かりづらいですね。
うーん、見た事あるパターンだと LsFIleList と LsFileにするとかだったら良いかなーと思いますがどうでしょう？

> 初期化時にインスタンス変数にしてしまうとnewした時しか呼ばれないです？
上のコードだとどうして呼ばれる回数が減るのか…？？？

これはイディオムでよくみるやつなですが、

````
@a ||= b
```
とすると、 @a がnullのときだけ bが呼ばれるので、 最初の一回だけbが動くようになります。

||=については https://docs.ruby-lang.org/ja/latest/doc/symref.html 参照。

> 初期化時にインスタンス変数にしてしまうとnewした時しか呼ばれないです？

この質問の意図がはっきり分かってないのですが、今の files_infoは file_names, total_fileblocks,find_max_sizeと3箇所から呼ばれているので少なくとも3回は呼ばれてるんだと思います。

2021-03-03 05:27 UTC, misosoup160 commented on 08.ls_object/lib/ls_file.rb
> +class LsFile
Ls::Fileにしようとしたんですが、FileクラスがもとからあるFileクラスと名前被りし、不具合が起きるので…Fileの名前を変えるかこのままにしとくかかなぁと…
あと、モジュールで囲った場合、ファイル構造が
`lib/ls/files.rb` （FileクラスとFilesクラス）
`lib/format.rb`
`lib/ls.rb`
ていう感じになるんでしょうか？

2021-03-03 05:31 UTC, misosoup160 commented on 08.ls_object/lib/ls_file.rb
> +  def format_type_and_mode
build_dataもバラして書いてみたのですが、max_sizesがちょっとスマートにかけませんでした！

2021-03-03 05:45 UTC, misosoup160 commented on 08.ls_object/lib/ls_files.rb
> +  def files_info
↓こういうことを考えていました。こうするとこのクラスのインスタンスが作られた時にだけインスタンス変数`@ls_files`が作られて、ls_filesメソッドは毎回よばれないのかな？と。
```
def initialize
    @ls_files = ls_files
end

def ls_files
    file_paths = collect_file_paths
    file_paths.map { |file_path| LsFile.new(file_path) }
end
```
オブジェクト指向設計ガイドの3章を読み返したら、ちゃんとインスタンスの作成を分離するのところにinitializeでインスタンス変数に入れるか、メソッドでインスタンス変数に入れるかで、メソッドのとこは`||=`で書いてありました。
これを付けとかないと毎回作成されるて感覚がなかったので不思議な感じがします…
でも中身が変わるかもしれないんだから当たり前か…

今回はメソッドでやる方がいいんでしょうか？
以前から「初期化でやることは初期化だけ」がちょっとピンときてなくて、基本的には引数で受けたものをインスタンス変数に入れるだけ！ってことなんでしょうか？

2021-03-03 10:16 UTC, u1tnk commented
返信しようとしたら元のコードが修正されてたのでできなかったので以下にインラインで回答します。

> ↓こういうことを考えていました。こうするとこのクラスのインスタンスが作られた時にだけインスタンス変数@ls_filesが作られて、ls_filesメソッドは毎回よばれないのかな？と。

```
def initialize
    @ls_files = ls_files
end

def ls_files
    file_paths = collect_file_paths
    file_paths.map { |file_path| LsFile.new(file_path) }
end
```
はい。初期化なので一回しかしない処理はそれでも大丈夫です。これであれば一回しか動かないので大丈夫です 🙆‍♀️ 

> 今回はメソッドでやる方がいいんでしょうか？
以前から「初期化でやることは初期化だけ」がちょっとピンときてなくて、基本的には引数で受けたものをインスタンス変数に入れるだけ！ってことなんでしょうか？

初期化でやることは初期化だけが原則ですが引数を受けるだけじゃなくても大丈夫です。
今回のように一回だけ情報を取得して保持しておく目的は初期化と言って良いですね。

メソッド呼ばれたときに `@hoge ||= ....` にするのは必要になるまで実行しない事に価値があって、オブジェクトが生成されるからといって使われない事もある場合に使うと良いです。
見慣れているのでつい使うように指示しましたが、 今回のケースでは必ず使われるので initializeでやるようにする方がシンプルで良さそうですね 👍

2021-03-03 10:17 UTC, u1tnk requested changes

2021-03-03 10:17 UTC, u1tnk commented on 08.ls_object/lib/ls_file.rb
> +class LsFile
`lib/format.rb`
↓
`lib/ls/format.rb`

になるかと思います。

> Ls::Fileにしようとしたんですが、FileクラスがもとからあるFileクラスと名前被りし、不具合が起きるので…Fileの名前を変えるかこのままにしとくかかなぁと…

その場合は元からあるFileは `::File`とすると区別できますね。
とはいえ、そういう手法もありますという話を伝えたかっただけなので、このままでも大丈夫です 🙆

2021-03-05 00:13 UTC, u1tnk requested changes
指摘しましたが細かいところばっかりです 👍

2021-03-05 00:13 UTC, u1tnk commented on 08.ls_object/lib/ls_files.rb
> +  def initialize(pathname, long_format: false, reverse: false, dot_match: false)
現状 long_formatは このクラスでは使ってないので初期化に入れないようにしましょう。Formatに直接渡せば良いですね。

2021-03-05 00:13 UTC, u1tnk commented on 08.ls_object/lib/ls_file.rb
> +  def fileblocks
build_dataとか消えてる！スッキリしましたね 😄

2021-03-05 00:13 UTC, u1tnk commented on 08.ls_object/lib/ls_files.rb
> +  def files
だいぶ細かい話ですが、 初期化でしか使わないので `initialized_files`とかの名前にしとくと、間違って使う事が無くなって良いと思います。
ls_filesとfilesどっちがどっちだっけ？？ってなりますし。

2021-03-05 00:13 UTC, u1tnk commented on 08.ls_object/lib/ls_files.rb
> +    ls_files.map(&:name)
細かい話ですが、クラス内では @ls_files を使った方がインスタンス変数そのまま使ってる感あって良いと思います。

2021-03-05 00:13 UTC, u1tnk commented on 08.ls_object/lib/ls_format.rb
> +class Format
クラス名とファイル名のルールは合わせたいので LsFormatとした方が良さそうです。

2021-03-05 00:13 UTC, u1tnk commented on 08.ls_object/lib/ls_format.rb
> +  def long_format_row(file, max_link, max_owner, max_group, max_size)
こことか max_sizesあたりもスッキリして何やってるか分かりやすくなりましたね 👍

2021-03-07 06:03 UTC, merged